apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: a8r
  name: a8r-controller
spec:
  replicas: 1
  selector:
    name: a8r
  template:
    metadata:
      labels:
        name: a8r
    spec:
      containers:
      - env:
        - name: KUBERNETES_TOKEN_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/token
        - name: KUBERNETES_CA_CERT_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        image: saturnism/a8r:v1
        name: a8r
        ports:
        - containerPort: 8080
          name: api
          protocol: TCP
