apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      name: infinispan
    name: infinispan-controller
  spec:
    replicas: 2
    selector:
      name: infinispan
    template:
      metadata:
        labels:
          name: infinispan
      spec:
        containers:
        - command:
          - /opt/jboss/infinispan-server/bin/clustered.sh
          - -c
          - clustered-google.xml
          - -b
          - '`hostname -I`'
          - -bmanagement=`hostname -I`
          - -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2
          - -Djboss.default.jgroups.stack=k8s
          - -Dkubeping.labels=infinispan
          - -Djgroups.tcp.external_addr=`hostname -I`
          - -Djboss.node.name=`hostname`
          - -Djboss.cluster.name=infinispan
          env:
          - name: JAVA_OPTS
            value: -Xmx512m -Xms512m -XX:PermSize=256m -XX:MaxPermSize=256m -XX:+UseConcMarkSweepGC
          - name: KUBERNETES_TOKEN_FILE
            value: /var/run/secrets/kubernetes.io/serviceaccount/token
          - name: KUBERNETES_CA_CERT_FILE
            value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          image: saturnism/infinite-infinispan:v1
          livenessProbe:
            tcpSocket:
              port: 8888
          name: infinispan
          ports:
          - containerPort: 7600
            name: jgroups
            protocol: TCP
          - containerPort: 57600
            name: jgroups-fd
            protocol: TCP
          - containerPort: 11222
            name: hotrod
            protocol: TCP
          - containerPort: 9990
            name: management-http
            protocol: TCP
          - containerPort: 8888
            name: ping
            protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8888
        - command:
          - /bin/sh
          - -c
          - java -cp jboss-client.jar:jmxtrans-247-SNAPSHOT-all.jar -Djava.net.preferIPv4Stack=true
            -Djava.awt.headless=true -Dinfinispan.host=${HOSTNAME} -Dinfinispan.port=9990
            -Dinfinispan.jmx.username=jmx -Dinfinispan.jmx.password=jmx -Dinfinispan.cache.name=default
            -Dk8s.replicationControllerId=infinispan-controller -Dk8s.podId=${HOSTNAME}
            -Da8r.url=http://${A8R_SERVICE_HOST}:${A8R_SERVICE_PORT}/a8r/metrics -Djmxtrans.log.dir=/app/
            com.googlecode.jmxtrans.JmxTransformer -f infinispan.json -s 10
          image: saturnism/jmxtrans-a8r-infinispan:v1
          name: jmxtrans
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      run: infinispan-visualizer
    name: infinispan-visualizer
  spec:
    replicas: 1
    selector:
      run: infinispan-visualizer
    template:
      metadata:
        labels:
          run: infinispan-visualizer
      spec:
        containers:
        - image: saturnism/infinispan-visualizer:v1
          name: infinispan-visualizer
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      run: demo
    name: demo
  spec:
    replicas: 1
    selector:
      run: demo
    template:
      metadata:
        labels:
          run: demo
      spec:
        containers:
        - image: saturnism/hotrod-demo:v1
          name: demo
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      name: a8r
    name: a8r-controller
  spec:
    replicas: 1
    selector:
      name: a8r
    template:
      metadata:
        labels:
          name: a8r
      spec:
        containers:
        - env:
          - name: KUBERNETES_TOKEN_FILE
            value: /var/run/secrets/kubernetes.io/serviceaccount/token
          - name: KUBERNETES_CA_CERT_FILE
            value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          image: saturnism/a8r:v1
          name: a8r
          ports:
          - containerPort: 8080
            name: api
            protocol: TCP
