apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    run: infinispan-visualizer
  name: infinispan-visualizer
spec:
  replicas: 1
  selector:
    run: infinispan-visualizer
  template:
    metadata:
      labels:
        run: infinispan-visualizer
    spec:
      containers:
      - image: saturnism/infinispan-visualizer:v1
        name: infinispan-visualizer
