apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: a8r
    name: a8r
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: api
    selector:
      name: a8r
    sessionAffinity: None
    type: LoadBalancer
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: infinispan
    name: infinispan
  spec:
    clusterIP: None
    ports:
    - port: 11222
      protocol: TCP
      targetPort: hotrod
    selector:
      name: infinispan
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      run: infinispan-visualizer
    name: infinispan-visualizer
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      run: infinispan-visualizer
    sessionAffinity: None
    type: LoadBalancer
